#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname -f)

if [[ -f "$DOKKU_ROOT/$APP/SLACK_URL" || -f "$DOKKU_ROOT/SLACK_URL" ]]; then
  echo "-----> Notifying Slack ..."
  URL=$(dokku url $APP)
  COMMIT_MESSAGE=$(cd /home/dokku/$APP && git log -1 --pretty=%B)

  SLACK_URL=$(cat "$DOKKU_ROOT/$APP/SLACK_URL" 2> /dev/null || cat "$DOKKU_ROOT/SLACK_URL" 2> /dev/null)
  SLACK_JSON="{ \
    \"attachments\": [{ \
      \"username\": \"deployment-bot\", \
      \"icon_url\": \"https://slack.com/img/icons/app-57.png\", \
      \"icon_emoji\": \":monkey_face:\", \
      \"text\": \"*$COMMIT_MESSAGE* - Deployed $APP to $HOSTNAME via $URL\", \
      \"fallback\": \"*$COMMIT_MESSAGE* - Deployed $APP to $HOSTNAME via $URL\", \
      \"color\": \"good\", \
      \"mrkdwn_in\": [\"text\"] \
    }] \
  }"
  SLACK_RESULT=$(curl -s -d "payload=$SLACK_JSON" "${SLACK_URL}" -w "%{http_code}")
  echo "       ${SLACK_RESULT}"
fi
